# Generated by Django 4.1.3
# 添加操作日志表

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('fater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            table='fater_operation_logs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, verbose_name='日志ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='用户ID', db_index=True)),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('user_type', models.IntegerField(verbose_name='用户类型')),
                ('operation_type', models.CharField(max_length=50, verbose_name='操作类型', db_index=True)),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名称', db_index=True)),
                ('resource_id', models.CharField(max_length=100, null=True, blank=True, verbose_name='资源ID')),
                ('resource_name', models.CharField(max_length=255, null=True, blank=True, verbose_name='资源名称')),
                ('operation_detail', models.TextField(null=True, blank=True, verbose_name='操作详情')),
                ('status', models.IntegerField(verbose_name='状态：1成功0失败')),
                ('error_message', models.TextField(null=True, blank=True, verbose_name='错误信息')),
                ('ip_address', models.CharField(max_length=50, null=True, blank=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(null=True, blank=True, verbose_name='用户代理')),
                ('device_type', models.CharField(max_length=50, null=True, blank=True, verbose_name='设备类型')),
                ('browser_type', models.CharField(max_length=50, null=True, blank=True, verbose_name='浏览器类型')),
                ('os_type', models.CharField(max_length=50, null=True, blank=True, verbose_name='操作系统')),
                ('location', models.CharField(max_length=100, null=True, blank=True, verbose_name='地理位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间', db_index=True)),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'fater_operation_logs',
                'ordering': ['-created_at'],
            },
            bases=(models.Model,),
        ),
    ]
