"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import pymysql
import os
import sys
import urllib.parse as urlparse
from typing import List


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')

# Optionally load .env for local/dev usage; production should pass env via process manager
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv()
except Exception:
    pass

# Configure pymysql to work with Django
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# Load configuration from environment for security and Docker compatibility
# DEBUG: 默认开发模式开启，生产环境请显式设置 DEBUG=False
DEBUG = _env_bool('DEBUG', True)

# SECRET_KEY: required in production; dev fallback only when DEBUG=True
secret_key_env = os.getenv('SECRET_KEY')
if secret_key_env:
    SECRET_KEY = secret_key_env
elif DEBUG:
    SECRET_KEY = 'dev-insecure-key-local-only-change-in-production'
else:
    raise RuntimeError('SECRET_KEY must be set in environment when DEBUG=False')

# ALLOWED_HOSTS: comma separated list in env, default to localhost for dev
ALLOWED_HOSTS: List[str] = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_yasg',
    'app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'comm.csrf_api_exempt_middleware.ApiCsrfExemptMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # ✅ 安全修复：启用 CSRF 保护
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TESTING = any(arg.startswith('test') for arg in sys.argv)

ENABLE_PERFORMANCE_MONITOR = _env_bool('ENABLE_PERFORMANCE_MONITOR', not TESTING)
if ENABLE_PERFORMANCE_MONITOR:
    MIDDLEWARE.insert(0, 'comm.performance_monitor.PerformanceMonitorMiddleware')

SLOW_REQUEST_THRESHOLD_MS = int(os.getenv('SLOW_REQUEST_THRESHOLD_MS', '1000'))
SLOW_DB_QUERY_THRESHOLD_MS = int(os.getenv('SLOW_DB_QUERY_THRESHOLD_MS', '200'))
ENABLE_DB_QUERY_OBSERVE = _env_bool('ENABLE_DB_QUERY_OBSERVE', DEBUG)

ENABLE_RATE_LIMIT = _env_bool('ENABLE_RATE_LIMIT', not TESTING)
if ENABLE_RATE_LIMIT:
    MIDDLEWARE.append('app.middleware.RateLimitMiddleware')

RATELIMIT_ENABLE = _env_bool('RATELIMIT_ENABLE', not TESTING)

# 查询监控中间件（仅在DEBUG模式下启用，暂时注释掉避免导入错误）
# if DEBUG:
#     try:
#         from app.comm.query_monitor import QueryMonitorMiddleware
#         MIDDLEWARE.append('app.comm.query_monitor.QueryMonitorMiddleware')
#     except ImportError:
#         pass

# CORS/CSRF settings (env-driven)
CORS_ALLOW_CREDENTIALS = True
cors_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_env.split(',') if o.strip()]
    CORS_ORIGIN_ALLOW_ALL = False
else:
    # 仅开发环境允许全开放，生产环境默认关闭
    CORS_ORIGIN_ALLOW_ALL = DEBUG
    CORS_ALLOWED_ORIGINS = []

csrf_exempt_prefixes_env = os.getenv('CSRF_EXEMPT_PATH_PREFIXES', '/api/')
CSRF_EXEMPT_PATH_PREFIXES = [p.strip() for p in csrf_exempt_prefixes_env.split(',') if p.strip()]

csrf_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_env.split(',') if o.strip()]

# 基础安全头
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
TRUST_PROXY_HEADERS = _env_bool('TRUST_PROXY_HEADERS', False)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)

# 缓存设置
# 开发环境直接使用内存缓存，生产环境可通过环境变量启用Redis
USE_REDIS = os.getenv('USE_REDIS', 'False').lower() == 'true'

if USE_REDIS:
    # 生产环境：尝试使用Redis
    REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
    REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
    REDIS_DB = int(os.getenv('REDIS_DB', '0'))
    REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)
    
    try:
        import redis
        # 测试Redis连接
        r = redis.Redis(
            host=REDIS_HOST,
            port=REDIS_PORT,
            db=REDIS_DB,
            password=REDIS_PASSWORD,
            socket_connect_timeout=2
        )
        r.ping()
        # Redis可用，使用Redis缓存
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'PASSWORD': REDIS_PASSWORD,
                    'SOCKET_CONNECT_TIMEOUT': 5,
                    'SOCKET_TIMEOUT': 5,
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'IGNORE_EXCEPTIONS': True,  # 缓存失败不影响主流程
                },
                'KEY_PREFIX': 'exam_cache',
                'TIMEOUT': 300,  # 默认5分钟过期
            }
        }
        print(f"✅ Redis缓存已启用: {REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}")
    except Exception as e:
        # Redis不可用，回退到内存缓存
        print(f"⚠️ Redis不可用 ({str(e)})，使用内存缓存")
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'TIMEOUT': 300,
            }
        }
else:
    # 开发环境：直接使用内存缓存（默认）
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': 300,  # 默认5分钟过期
        }
    }
    # 不显示警告信息，静默使用内存缓存

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

def _db_from_database_url(url):
    """Parse DATABASE_URL like mysql://user:pass@host:port/dbname"""
    parsed = urlparse.urlparse(url)
    return {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': parsed.path.lstrip('/') or os.getenv('DB_NAME', 'db_exam'),
        'USER': urlparse.unquote(parsed.username) if parsed.username else os.getenv('DB_USER', 'examuser'),
        'PASSWORD': urlparse.unquote(parsed.password) if parsed.password else os.getenv('DB_PASSWORD', 'exam123456'),
        'HOST': parsed.hostname or os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': parsed.port or int(os.getenv('DB_PORT', 3306)),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES utf8mb4, sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
            'read_timeout': 30,
            'write_timeout': 30,
        },
        'CONN_MAX_AGE': 600,
        'ATOMIC_REQUESTS': False,
    }


# Support DATABASE_URL env (used by docker-compose) or individual DB_* vars
database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES = {'default': _db_from_database_url(database_url)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'db_exam'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': int(os.getenv('DB_PORT', 3306)),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET NAMES utf8mb4, sql_mode='STRICT_TRANS_TABLES'",
                'connect_timeout': 10,
                'read_timeout': 30,
                'write_timeout': 30,
            },
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': False,
        }
    }


# Password validation
# Django直接使用LOGGING字典，从logging_config模块导入
try:
    from server.logging_config import LOGGING
except (ImportError, AttributeError, Exception) as e:
    # 如果导入失败，使用默认配置
    import logging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'app': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ============================================
# 编码配置 - 解决中文乱码问题
# ============================================
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'

# 数据库连接编码
DATABASE_OPTIONS = {
    'charset': 'utf8mb4',
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
}


# Static and media files (env-driven for production deploys)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')

# Where collectstatic should place files (used by Nginx alias)
STATIC_ROOT = os.getenv('STATIC_ROOT', str(Path('/app/static')))
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(Path('/app/media')))

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 智谱AI配置（使用环境变量，避免硬编码）
# 支持 ZHIPUAI_* 变量名（与 env.example 对齐），若不存在则兼容 OPENAI_* 命名
ZHIPUAI_API_KEY = os.getenv('ZHIPUAI_API_KEY') or os.getenv('OPENAI_API_KEY') or ''
ZHIPUAI_MODEL = os.getenv('ZHIPUAI_MODEL') or os.getenv('OPENAI_MODEL') or 'glm-4-flash'
ZHIPUAI_BASE_URL = os.getenv('ZHIPUAI_BASE_URL') or os.getenv('OPENAI_BASE_URL') or 'https://open.bigmodel.cn/api/paas/v4'
# ============================================
# 测试数据库配置
# 当运行测试时，使用SQLite内存数据库以加速测试
# ============================================

import sys

IS_TESTING = 'test' in sys.argv

if IS_TESTING:
    # 测试环境使用SQLite内存数据库（快速、无需MySQL）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',  # 内存数据库，测试后自动清理
            'ATOMIC_REQUESTS': True,  # 每个请求在事务中执行
        }
    }

    # 测试时简化密码验证
    AUTH_PASSWORD_VALIDATORS = []

    print("==========================================")
    print("测试模式：使用SQLite内存数据库")
    print("==========================================")
