# Generated by Django 4.1.3 on 2026-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_users_password_delete_messageattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passWord',
            field=models.CharField(db_column='pass_word', max_length=100, verbose_name='用���密码'),
        ),
    ]
