# Generated by Django 4.1.3 on 2026-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_operation_logs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagereads',
            index=models.Index(fields=['message'], name='idx_messagereads_message'),
        ),
        migrations.AddIndex(
            model_name='messagereads',
            index=models.Index(fields=['user'], name='idx_messagereads_user'),
        ),
        migrations.AddIndex(
            model_name='messagereads',
            index=models.Index(fields=['isRead'], name='idx_messagereads_isread'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender'], name='idx_messages_sender'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['type'], name='idx_messages_type'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['priority'], name='idx_messages_priority'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['createTime'], name='idx_messages_createtime'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['grade'], name='idx_students_grade'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['college'], name='idx_students_college'),
        ),
        migrations.AddIndex(
            model_name='studenttaskanswers',
            index=models.Index(fields=['taskLog'], name='idx_taskanswers_tasklog'),
        ),
        migrations.AddIndex(
            model_name='studenttaskanswers',
            index=models.Index(fields=['practise'], name='idx_taskanswers_practise'),
        ),
        migrations.AddIndex(
            model_name='studenttaskanswers',
            index=models.Index(fields=['answerTime'], name='idx_taskanswers_answertime'),
        ),
        migrations.AddIndex(
            model_name='taskquestions',
            index=models.Index(fields=['task'], name='idx_taskquestions_task'),
        ),
        migrations.AddIndex(
            model_name='taskquestions',
            index=models.Index(fields=['practise'], name='idx_taskquestions_practise'),
        ),
        migrations.AddIndex(
            model_name='wrongquestionreviews',
            index=models.Index(fields=['wrongQuestion'], name='idx_wrongreviews_wrongquestion'),
        ),
        migrations.AddIndex(
            model_name='wrongquestions',
            index=models.Index(fields=['student'], name='idx_wrongquestions_student'),
        ),
        migrations.AddIndex(
            model_name='wrongquestions',
            index=models.Index(fields=['practise'], name='idx_wrongquestions_practise'),
        ),
        migrations.AddIndex(
            model_name='wrongquestions',
            index=models.Index(fields=['isReviewed'], name='idx_wrongquestions_isreviewed'),
        ),
        migrations.AddIndex(
            model_name='wrongquestions',
            index=models.Index(fields=['createTime'], name='idx_wrongquestions_createtime'),
        ),
    ]
