# Generated by Django 4.1.3 on 2026-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_operationlog_id_alter_users_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticelogs',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='users',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_time', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='users',
            name='lastLoginTime',
            field=models.DateTimeField(db_column='last_login_time', null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='日志ID'),
        ),
        migrations.AlterField(
            model_name='practises',
            name='type',
            field=models.IntegerField(choices=[(0, '选择题'), (1, '填空题'), (2, '判断题'), (3, '编程题')], verbose_name='题目类型 0-选择 1-填空 2-判断 3-编程'),
        ),
        migrations.AlterField(
            model_name='users',
            name='passWord',
            field=models.CharField(db_column='pass_word', max_length=128, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '教师'), (2, '学生')], verbose_name='用户身份 0-管理员 1-教师 2-学生'),
        ),
    ]
