# Generated by Django 4.1.3 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_studentpracticelogs_createtime_users_createtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practises',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度等级'),
        ),
        migrations.AddField(
            model_name='practises',
            name='tags',
            field=models.JSONField(default=list, verbose_name='知识点标签'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '禁用'), (2, '锁定')], default=0, verbose_name='账户状态'),
        ),
        migrations.AddField(
            model_name='wrongquestions',
            name='masteryLevel',
            field=models.SmallIntegerField(choices=[(0, '未复习'), (1, '复习中'), (2, '已掌握')], default=0, verbose_name='掌握程度'),
        ),
        migrations.AddIndex(
            model_name='answerlogs',
            index=models.Index(fields=['exam', 'student', 'practise'], name='fater_answe_exam_id_7345fc_idx'),
        ),
        migrations.AddIndex(
            model_name='examlogs',
            index=models.Index(fields=['exam', 'status'], name='fater_exam__exam_id_70fe18_idx'),
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['user', 'grade'], name='fater_stude_user_id_eb538c_idx'),
        ),
        migrations.AddIndex(
            model_name='wrongquestions',
            index=models.Index(fields=['student', 'isReviewed'], name='fater_wrong_student_85d8e0_idx'),
        ),
    ]
