# Generated by Django 4.1.3 on 2026-02-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_practises_difficulty_practises_tags_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('fileName', models.CharField(max_length=255, null=False, verbose_name='文件名称')),
                ('filePath', models.CharField(max_length=500, null=False, verbose_name='文件路径')),
                ('fileSize', models.IntegerField(null=False, verbose_name='文件大小(字节)')),
                ('fileType', models.CharField(max_length=20, null=False, verbose_name='文件类型')),
                ('uploadTime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('downloadCount', models.IntegerField(default=0, verbose_name='下载次数')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tasks', verbose_name='关联任务')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'fater_task_attachments',
                'ordering': ['-uploadTime'],
            },
        ),
        migrations.CreateModel(
            name='UserThemeSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('theme', models.CharField(default='light', help_text='light/dark', max_length=50, verbose_name='主题名称')),
                ('primaryColor', models.CharField(default='#2d8cf0', max_length=20, verbose_name='主题色')),
                ('fontSize', models.CharField(default='medium', help_text='small/medium/large', max_length=10, verbose_name='字体大小')),
                ('sidebarCollapsed', models.BooleanField(default=False, verbose_name='侧边栏折叠')),
                ('showAnimations', models.BooleanField(default=True, verbose_name='显示动画')),
                ('compactMode', models.BooleanField(default=False, verbose_name='紧凑模式')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户主题设置',
                'verbose_name_plural': '用户主题设置',
                'db_table': 'fater_user_theme_settings',
            },
        ),
        migrations.AddIndex(
            model_name='taskattachments',
            index=models.Index(fields=['task'], name='idx_taskattachments_task'),
        ),
        migrations.AddIndex(
            model_name='taskattachments',
            index=models.Index(fields=['uploadTime'], name='idx_taskattachments_uploadtime'),
        ),
    ]
