# Generated by Django 4.1.3 on 2026-02-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_attachments_and_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practises',
            name='type',
            field=models.IntegerField(choices=[(0, '选择题'), (1, '填空题'), (2, '判断题'), (3, '简答题'), (4, '编程题'), (5, '综合题')], verbose_name='题目类型 0-选择 1-填空 2-判断 3-编程'),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='app.tasks', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='uploadedBy',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users', verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='userthemesettings',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='用户'),
        ),
    ]
