# Generated by Django 4.1.3 on 2026-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_practises_type_alter_taskattachments_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('user_type', models.IntegerField(blank=True, null=True, verbose_name='用户类型')),
                ('operation_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('export', '导出'), ('import', '导入'), ('submit', '提交'), ('review', '审核'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('operation_desc', models.CharField(max_length=255, verbose_name='操作描述')),
                ('module', models.CharField(max_length=50, verbose_name='模块名称')),
                ('target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='对象ID')),
                ('target_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='对象名称')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求路径')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='操作状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='变更前值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='变更后值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'fater_audit_logs',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id'], name='fater_audit_user_id_4a9d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operation_type'], name='fater_audit_operati_2ac93b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module'], name='fater_audit_module_53e0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['create_time'], name='fater_audit_create__621b97_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status'], name='fater_audit_status_e9b4aa_idx'),
        ),
    ]
